server:
  port: 80
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: com.aiops.api.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.aiops.api.config.mybatis.typehandler

mapper:
  mappers:
    - com.aiops.api.config.MyMapper
  not-empty: true
  identity: MYSQL

aiops:
  paging:
    size: 15
  step:
    reserved-number: 2000

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  helper-dialect: mysql
  support-methods-arguments: true
  pageSizeZero: true
---
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/aiops?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true

logging:
  level:
    com:
      aiops:
        api:
          mapper: debug

---
spring:
  profiles: prod
  datasource:
    username: kdm
    password: aiops-api
    url: jdbc:mysql://localhost:3306/aiops?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true