#默认使用配置

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources

#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yummy?useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: 1998
    driver-class-name: com.mysql.jdbc.Driver
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource